services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
