version: '3.8'
services:
  mongo:
    image: mongo
    container_name: owo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: ./src  # Specifies the 'src' folder for building the Dockerfile
      dockerfile: Dockerfile  # Explicitly states the Dockerfile to use in 'src'
    container_name: owoo-app
    ports:
      - "3000:80"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/owo_db

volumes:
  mongo-data:
