version: '3'
services:
  mongo:
    image: mongo
    container_name: owo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: owo-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/owo_db

volumes:
  mongo-data:
